name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
          ninja: true

      - name: Install Emscripten
        run: |
          chmod +x ./scripts/install-emscripten.sh ./scripts/activate-emscripten.sh
          ./scripts/install-emscripten.sh
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build
        run: |
          ./scripts/activate-emscripten.sh
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifact"
          if-no-files-found: error
          path: ${{ env.BUILD_PATH }}/dist
