name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ["Debug", "MinSizeRel"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Emscripten
        run: npm run setup
        
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          cmake: true
          ninja: true

      - name: Build
        run: npm run build "${{ matrix.configuration }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "build-${{ matrix.configuration }}"
          if-no-files-found: error
          path: ./dist
